"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";
import AiButton from "@/components/AiButton";

import { createContext } from "react";
import { AuthProvider } from "@/context/AuthContext";
import { toast, ToastContainer } from "react-toastify";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const ThemeContext = createContext({ name: '' });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex relative">
        <AuthProvider>
          <Sidebar />
          <div className="w-full relative">
            <Navbar />
            <div className="px-5 md:px-10">
              {children}
            </div>
          <Footer />
          </div>

          <AiButton />
          <ToastContainer position="bottom-right" />
        </AuthProvider>
      </body>
    </html>
  );
}
